#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HangmanWordGame.Resource", IsApplication=true)]

namespace HangmanWordGame
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020001
			public const int btnA = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int btnAddProfile = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnB = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int btnBackTomainmenu = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int btnC = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int btnD = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int btnDeleteEntry = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int btnE = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int btnEditDatabase = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int btnEditDbBackToMainMenu = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int btnF = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int btnG = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int btnGobackToMainMenu = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int btnH = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int btnHighScore = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int btnI = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int btnJ = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int btnK = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int btnL = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int btnM = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int btnN = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int btnO = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int btnP = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int btnQ = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int btnQuitGame = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int btnR = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int btnS = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int btnStartGame = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int btnStartNewGameScreen = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int btnT = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int btnU = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int btnV = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int btnW = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int btnX = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int btnY = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int btnZ = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int gamebtnMainMenu = 2130837541;
			
			// aapt resource value: 0x7F020000
			public const int HighScoresListView = 2130837504;
			
			// aapt resource value: 0x7F020026
			public const int imgHangmanMain = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int imgHangmanPlayerProfile = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int imgHangmanWordGame = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int linearLayout1 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int linearLayout2 = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int linearLayout3 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int linearLayout4 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int linearLayout5 = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int selectPlayerSpinner = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int spinnereditDB = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int textView1 = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int textView2 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int textView3 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int textViewCurrentScore = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int textViewGuessesLeft = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int textViewh1 = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int txtCurrentScore = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int txtEnterName = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int txtGuessesLeft = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int txtHighScores = 2130837561;
			
			// aapt resource value: 0x7F02003B
			public const int txtrowId = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int txtrowName = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int txtrowScore = 2130837565;
			
			// aapt resource value: 0x7F02003A
			public const int txtWordToGuess = 2130837562;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030005
			public const int activity_main = 2130903045;
			
			// aapt resource value: 0x7F030000
			public const int AddPlayerProfile = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int EditDatabase = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int HighScoreCard = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ListViewRow = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int MainGame_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int gameover_lose = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int gameover_win = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int hang0 = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int hang1 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int hang2 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int hang3 = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int hang4 = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int hang5 = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int hang6 = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_launcher = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_launcher_foreground = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_launcher_round = 2130968588;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
